const products = [
    {
        id: 1,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
        status: "new",
    },
    {
        id: 2,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
        status: "hit",
    },
    {
        id: 3,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 4,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 5,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 6,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 7,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 8,
        name: "Бургер",
        price: 122,
        delivery: true,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 9,
        name: "Бургер",
        price: 122,
        delivery: false,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 10,
        name: "Бургер",
        price: 122,
        delivery: false,
        img: "http://localhost:3003/burger.png",
    },
    {
        id: 11,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 12,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 13,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 14,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 15,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 16,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 17,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 18,
        name: "Твистер",
        price: 144,
        delivery: true,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 19,
        name: "Твистер",
        price: 144,
        delivery: false,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 20,
        name: "Твистер",
        price: 144,
        delivery: false,
        img: "http://localhost:3003/twister.png",
    },
    {
        id: 21,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 22,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 23,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 24,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 25,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 26,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 27,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 28,
        name: "Стрипсы",
        price: 160,
        delivery: true,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 29,
        name: "Стрипсы",
        price: 160,
        delivery: false,
        img: "http://localhost:3003/strips.png",
    },
    {
        id: 30,
        name: "Стрипсы",
        price: 160,
        delivery: false,
        img: "http://localhost:3003/strips.png",
    },
];

module.exports = products;
